export const REQUEST_ROOM_DETAIL = "@TrangChiTietPhong/REQUEST_ROOM_DETAIL";
export const REQUEST_ROOM_DETAIL_SUCCESS =
  "@TrangChiTietPhong/REQUEST_ROOM_DETAIL_SUCCESS";
export const REQUEST_ROOM_DETAIL_ERROR =
  "@TrangChiTietPhong/REQUEST_ROOM_DETAIL_ERROR";

