export const REQUEST_BOOKING_ROOM = "@TrangDatPhong/REQUEST_BOOKING_ROOM";
export const REQUEST_BOOKING_ROOM_SUCCESS =
  "@TrangDatPhong/REQUEST_BOOKING_ROOM_SUCCESS";
export const REQUEST_BOOKING_ROOM_ERROR =
  "@TrangDatPhong/REQUEST_BOOKING_ROOM_ERROR";
